name: Lint Test Deploy On Push
on: push
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Lint Code
        run: |
          npm run lint
          echo "Linting code..."
  Test:
    runs-on: ubuntu-latest
    needs: Lint
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Testing code
        run: npm run test
  Deploy:
    runs-on: ubuntu-latest
    needs: Test
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: build code
        run: npm run build
      - name: deploy code
        run: echo "Deploying..."
