name: Output Event Details on Issues
on:
  issues:
    types: [opened, edited, milestoned]
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Outputting event details
        run: echo "${{toJSON(github)}}"
