name: Lint Test Deploy On Push
on: push
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Lint Code
        run: |
          npm run lint
          echo "Linting code..."
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Testing code
        run: npm run test
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: build code
        run: npm run build
